In [1]:
import pandas as pd

In [54]:
data_model_df = pd.read_excel("../data/external/Data Model - Draft - for SI Union List - Populated.xlsx", sheet_name="Sheet1")

is_dtype = {"Block Number": "Int64", "Sheet Number": "Int64", "Date.1": "str", "Date.2": "str", "Date.3": "str", "Drawer": "Int64"}
is_df = pd.read_excel("../data/raw/Maps IS.xlsx", sheet_name="54 RAW", skiprows=5, header=None, names=["Block Number", "Block Letter", "Sheet Number", "Date.1", "Date.2", "Date.3", "Drawer", "Shelfmark", "Extra Date.1", "Extra Date.2"], dtype=is_dtype)
is_df.drop(index=0, inplace=True)
is_gt_df = pd.read_excel("../data/raw/Maps IS.xlsx", sheet_name="54 NEW")

x9_df = pd.read_excel("../data/raw/X_9053.xlsx", sheet_name="54 Raw", skiprows=6, skipfooter=4, header=None, usecols=[0,1], names=["Block String", "Full Reference"])
x9_gt_df = pd.read_excel("../data/raw/X_9053.xlsx", sheet_name="54 New")

C:\Users\hlloyd\projects\union-lists\.venv\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
C:\Users\hlloyd\projects\union-lists\.venv\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
C:\Users\hlloyd\projects\union-lists\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [55]:
data_model_df.columns

Index(['Attribute', 'Series Title', 'Scale', 'Location Room',
       'Location Section', 'Location Detail', 'Full Reference',
       'Parent Reference', 'Block Number', 'Block Letter', 'Sheet Number',
       'Sheet Title', 'Edition Number', 'Edition Date', 'Designation_1',
       'Designation_2', 'Publication Date', 'Print Date', 'Print Reference',
       'Copies Printed', 'Coloured', 'Gridded', 'Number of Copies', 'Repmat',
       'Longitude', 'Latitude', 'Available'],
      dtype='str')

In [29]:
is_df.columns

Index(['Block Number', 'Block Letter', 'Sheet Number', 'Date.1', 'Date.2',
       'Date.3', 'Drawer', 'Shelfmark', 'Extra Date.1', 'Extra Date.2'],
      dtype='str')

In [30]:
include_if_present = ["Date.2", "Date.3", "Extra Date.1", "Extra Date.2"]
by_date = [is_df.drop(columns=include_if_present).rename(columns={"Date.1": "Date"})]
for col in include_if_present:
    by_date.append(is_df[['Block Number', 'Block Letter', 'Sheet Number', 'Drawer', 'Shelfmark'] + [col]].dropna(subset=col).rename(columns={col: "Date"}))

In [31]:
clean_is_df = pd.concat(by_date).sort_values(["Block Number", "Block Letter", "Sheet Number"]).reset_index(drop=True)
clean_is_df["Village Boundaries"] = clean_is_df["Date"].str.contains("vb")
clean_is_df["Date"] = clean_is_df["Date"].str.strip(" vb").str.strip("&")

In [32]:
clean_is_df

,Block Number,Block Letter,Sheet Number,Date,Drawer,Shelfmark,Village Boundaries
0,54,A,1,1919,470,Maps IS 327 + 328,False
1,54,A,1,1947,470,Maps IS 327 + 328,False
2,54,A,2,NaN,<NA>,NaN,False
3,54,A,3,NaN,<NA>,NaN,False
4,54,A,4,NaN,<NA>,NaN,False
...,...,...,...,...,...,...,...
379,54,P,14,1947,473,Maps IS 333 +334,False
380,54,P,15,1927,473,Maps IS 333 +334,False
381,54,P,15,1947,473,Maps IS 333 +334,False
382,54,P,16,1909,473,Maps IS 333 +334,False
383,54,P,16,1947,473,Maps IS 333 +334,False

In [33]:
expected_output_length = is_df.shape[0] + is_df.dropna(subset="Date.2").shape[0] + is_df.dropna(subset="Date.3").shape[0] + is_df.dropna(subset="Extra Date.1").shape[0] + is_df.dropna(subset="Extra Date.2").shape[0]

In [34]:
assert expected_output_length == clean_is_df.shape[0]
assert expected_output_length == is_gt_df.shape[0]

AssertionError:

In [48]:
is_gt_df.head()

   SHEET Unnamed: 1  Unnamed: 2         SHELF MARK    DATE Date Class Notes
0     54          A           1  Maps IS 327 + 328  1919.0      1905>   NaN
1     54          A           1  Maps IS 327 + 328  1947.0      1905>   NaN
2     54          A           2                NaN     NaN        NaN   NaN
3     54          A           3                NaN     NaN        NaN   NaN
4     54          A           4                NaN     NaN        NaN   NaN

In [56]:
x9_df.head()

  Block String          Full Reference
0        54A/1       X/9053/54A/1 1919
1        54A/2                     NaN
2        54A/3                     NaN
3        54A/4                     NaN
4        54A/5  X/9053/54A/5 1891/1924

In [57]:
x9_df.shape

(306, 2)

In [74]:
pd.isna(x9_df.head().loc[2, "Full Reference"])

True

In [83]:
def split_block(s: str|pd.NA) -> (str, str, str)|(pd.NA, pd.NA, pd.NA):
    if pd.isna(s):
        return (pd.NA, pd.NA, pd.NA)
        
    n = s.split("/")[0][:-1]
    l = s.split("/")[0][-1]
    sn = s.split("/")[1]
    return (n, l, sn)

In [84]:
def split_ref(s: str|pd.NA) -> str|pd.NA:
    if pd.isna(s):
        return pd.NA

    date = s.split()[-1]
    return date

In [85]:
clean_x9_df = pd.DataFrame(columns=data_model_df.columns)
clean_x9_df["Full Reference"] = x9_df["Full Reference"]
x9_df["Block Split"] = x9_df["Block String"].apply(lambda x: split_block(x))
clean_x9_df["Block Number"] = x9_df["Block Split"].apply(lambda x: x[0])
clean_x9_df["Block Letter"] = x9_df["Block Split"].apply(lambda x: x[1])
clean_x9_df["Sheet Number"] = x9_df["Block Split"].apply(lambda x: x[2])
clean_x9_df["Publication Date"] = clean_x9_df["Full Reference"].apply(lambda x: split_ref(x))

In [86]:
clean_x9_df.head()

,Attribute,Series Title,Scale,Location Room,Location Section,Location Detail,Full Reference,Parent Reference,Block Number,Block Letter,...,Print Date,Print Reference,Copies Printed,Coloured,Gridded,Number of Copies,Repmat,Longitude,Latitude,Available
0,NaN,NaN,NaN,NaN,NaN,NaN,X/9053/54A/1 1919,NaN,54,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,X/9053/54A/5 1891/1924,NaN,54,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
x9_gt_df.head()

   Block Letter  Number               Reference  Unnamed: 4 Date Class Notes
0     54      A       1       X/9053/54A/1 1919      1919.0      1905>   NaN
1     54      A       2                     NaN         NaN        NaN   NaN
2     54      A       3                     NaN         NaN        NaN   NaN
3     54      A       4                     NaN         NaN        NaN   NaN
4     54      A       5  X/9053/54A/5 1891/1924      1924.0      1905>   NaN